// Balance configuration — auto-generated by self-play balance loop
// Generated: 2026-08-08T13:03:33.673Z
// Cycle: 2 | Win rate: 32.0% | Diversity: 77%
// Manual edits will be overwritten on next balance cycle.
// To play with default (untuned) values, set window.__BALANCE_OVERRIDES = {};
window.__BALANCE_OVERRIDES = {
  "UNIT_DEFS[4].dps": 14,
  "UNIT_DEFS[4].cooldown": 1.1,
  "WAVE_HP_SCALING": 0.07,
  "WAVE_SPEED_SCALING": 0.055,
  "WAVE_INCOME_BASE": 6,
  "UNIT_DEFS[0].hp": 420,
  "UNIT_DEFS[1].hp": 210,
  "UNIT_DEFS[2].hp": 63,
  "UNIT_DEFS[3].hp": 263,
  "UNIT_DEFS[4].hp": 84,
  "UNIT_DEFS[5].hp": 189,
  "UPGRADE_COST_FRACTION_TIER1": 0.29000000000000004,
  "UPGRADE_COST_FRACTION_TIER2": 0.35
};
