/**
 * Config Writer
 * Writes balance configurations as versioned files and updates the
 * live balance-config.js that the game HTML loads.
 *
 * Unattended cloud/CI runs set BALANCE_GIT_USER_NAME / BALANCE_GIT_USER_EMAIL
 * or fall back to hormuz-self-play-bot. Push auth uses GITHUB_TOKEN or GIT_TOKEN
 * when present (HTTPS remote rewrite).
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const REPO_ROOT = path.join(__dirname, '..');
const CONFIGS_DIR = path.join(__dirname, 'configs');
const LIVE_CONFIG = path.join(REPO_ROOT, 'balance-config.js');
const DEFAULT_BRANCH = 'self-play';

/** True when running under CI, GitHub Actions, or Cursor Cloud Agent VM. */
function isUnattendedRun() {
    return !!(
        process.env.CI
        || process.env.CURSOR_CLOUD
        || process.env.GITHUB_ACTIONS
    );
}

/** Default git author for balance bot commits. */
function defaultGitIdentity() {
    return {
        name: process.env.BALANCE_GIT_USER_NAME || 'hormuz-self-play-bot',
        email: process.env.BALANCE_GIT_USER_EMAIL || 'hormuz-self-play-bot@users.noreply.github.com',
    };
}

/**
 * Ensure local git user.name / user.email exist (repo-local config only).
 */
function ensureGitIdentity() {
    const opts = { cwd: REPO_ROOT, stdio: 'pipe' };
    let hasName = false;
    let hasEmail = false;
    try {
        execSync('git config --local user.name', opts);
        hasName = true;
    } catch (_) { /* unset */ }
    try {
        execSync('git config --local user.email', opts);
        hasEmail = true;
    } catch (_) { /* unset */ }

    const { name, email } = defaultGitIdentity();
    if (!hasName) {
        execSync(`git config --local user.name ${JSON.stringify(name)}`, opts);
    }
    if (!hasEmail) {
        execSync(`git config --local user.email ${JSON.stringify(email)}`, opts);
    }
}

/**
 * When GITHUB_TOKEN or GIT_TOKEN is set, rewrite origin for HTTPS push auth.
 */
function configurePushAuth() {
    const token = process.env.GITHUB_TOKEN || process.env.GIT_TOKEN;
    if (!token) return;

    const opts = { cwd: REPO_ROOT, stdio: 'pipe', encoding: 'utf8' };
    let remoteUrl = '';
    try {
        remoteUrl = execSync('git remote get-url origin', opts).trim();
    } catch (_) {
        return;
    }

    if (remoteUrl.includes('x-access-token@') || remoteUrl.includes(`${token}@`)) {
        return;
    }

    const match = remoteUrl.match(/github\.com[:/]([^/]+)\/([^/.]+)(?:\.git)?$/);
    if (!match) return;

    const [, owner, repo] = match;
    const authed = `https://x-access-token:${token}@github.com/${owner}/${repo}.git`;
    execSync(`git remote set-url origin ${JSON.stringify(authed)}`, opts);
}

/**
 * Format overrides object as a balance-config.js file.
 */
function formatConfigJS(overrides, metadata = {}) {
    const lines = [
        '// Balance configuration — auto-generated by self-play balance loop',
        `// Generated: ${metadata.timestamp || new Date().toISOString()}`,
        `// Cycle: ${metadata.cycle || '?'} | Win rate: ${metadata.winRate || '?'}% | Diversity: ${metadata.diversity || '?'}%`,
        '// Manual edits will be overwritten on next balance cycle.',
        '// To play with default (untuned) values, set window.__BALANCE_OVERRIDES = {};',
        `window.__BALANCE_OVERRIDES = ${JSON.stringify(overrides, null, 2)};`,
        '',
    ];
    return lines.join('\n');
}

/**
 * Write a timestamped config to self-play/configs/ and update the live config.
 */
function writeConfig(overrides, metadata = {}) {
    if (!fs.existsSync(CONFIGS_DIR)) {
        fs.mkdirSync(CONFIGS_DIR, { recursive: true });
    }

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const cycle = metadata.cycle || 0;
    const filename = `config-${timestamp}-cycle${cycle}.json`;
    const configPath = path.join(CONFIGS_DIR, filename);

    const archival = {
        overrides,
        metadata: {
            ...metadata,
            timestamp: new Date().toISOString(),
        },
    };
    fs.writeFileSync(configPath, JSON.stringify(archival, null, 2));

    const configJS = formatConfigJS(overrides, metadata);
    fs.writeFileSync(LIVE_CONFIG, configJS);

    return { configPath, filename };
}

/** True if the index has staged changes after git add. */
function hasStagedChanges() {
    try {
        execSync('git diff --cached --quiet', { cwd: REPO_ROOT, stdio: 'pipe' });
        return false;
    } catch (_) {
        return true;
    }
}

/**
 * Git add and commit config changes.
 * Returns { ok, hash?, skipped?, error? }.
 */
function commitConfig(metadata = {}) {
    const cycle = metadata.cycle || '?';
    const winRate = metadata.winRate || '?';
    const diversity = metadata.diversity || '?';

    const msg = [
        `balance: cycle ${cycle} — win ${winRate}% div ${diversity}%`,
        '',
        'Auto-generated by self-play balance loop.',
        'Overrides applied to balance-config.js.',
    ].join('\n');

    try {
        ensureGitIdentity();

        execSync('git add balance-config.js self-play/configs/ self-play/balance-result.json', {
            cwd: REPO_ROOT,
            stdio: 'pipe',
        });

        if (!hasStagedChanges()) {
            return { ok: true, skipped: true, hash: null };
        }

        const msgPath = path.join(REPO_ROOT, '.git', 'BALANCE_COMMIT_MSG');
        fs.writeFileSync(msgPath, msg);
        try {
            execSync('git commit -F .git/BALANCE_COMMIT_MSG', {
                cwd: REPO_ROOT,
                stdio: 'pipe',
            });
        } finally {
            try { fs.unlinkSync(msgPath); } catch (_) { /* ignore */ }
        }

        const hash = execSync('git rev-parse --short HEAD', {
            cwd: REPO_ROOT,
            stdio: 'pipe',
        }).toString().trim();

        return { ok: true, hash };
    } catch (e) {
        const error = e.stderr ? e.stderr.toString() : e.message;
        console.error(`Git commit failed: ${error}`);
        return { ok: false, error };
    }
}

/**
 * Push to remote self-play branch.
 * Returns { ok, error? }.
 */
function pushConfig(branch = DEFAULT_BRANCH) {
    try {
        ensureGitIdentity();
        configurePushAuth();

        execSync(`git push -u origin ${branch}`, {
            cwd: REPO_ROOT,
            stdio: 'pipe',
            timeout: 60000,
        });
        return { ok: true };
    } catch (e) {
        const error = e.stderr ? e.stderr.toString() : e.message;
        console.error(`Git push failed: ${error}`);
        return { ok: false, error };
    }
}

module.exports = {
    writeConfig,
    commitConfig,
    pushConfig,
    formatConfigJS,
    isUnattendedRun,
    defaultGitIdentity,
    ensureGitIdentity,
    configurePushAuth,
};
