/**
 * Config Writer
 * Writes balance configurations as versioned files and updates the
 * live balance-config.js that the game HTML loads.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const REPO_ROOT = path.join(__dirname, '..');
const CONFIGS_DIR = path.join(__dirname, 'configs');
const LIVE_CONFIG = path.join(REPO_ROOT, 'balance-config.js');

/**
 * Format overrides object as a balance-config.js file.
 */
function formatConfigJS(overrides, metadata = {}) {
    const lines = [
        '// Balance configuration — auto-generated by self-play balance loop',
        `// Generated: ${metadata.timestamp || new Date().toISOString()}`,
        `// Cycle: ${metadata.cycle || '?'} | Win rate: ${metadata.winRate || '?'}% | Diversity: ${metadata.diversity || '?'}%`,
        '// Manual edits will be overwritten on next balance cycle.',
        '// To play with default (untuned) values, set window.__BALANCE_OVERRIDES = {};',
        `window.__BALANCE_OVERRIDES = ${JSON.stringify(overrides, null, 2)};`,
        '',
    ];
    return lines.join('\n');
}

/**
 * Write a timestamped config to self-play/configs/ and update the live config.
 * Returns the path to the timestamped config file.
 */
function writeConfig(overrides, metadata = {}) {
    // Ensure configs directory exists
    if (!fs.existsSync(CONFIGS_DIR)) {
        fs.mkdirSync(CONFIGS_DIR, { recursive: true });
    }

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const cycle = metadata.cycle || 0;
    const filename = `config-${timestamp}-cycle${cycle}.json`;
    const configPath = path.join(CONFIGS_DIR, filename);

    // Write timestamped JSON config (archival)
    const archival = {
        overrides,
        metadata: {
            ...metadata,
            timestamp: new Date().toISOString(),
        },
    };
    fs.writeFileSync(configPath, JSON.stringify(archival, null, 2));

    // Write live balance-config.js (what the game loads)
    const configJS = formatConfigJS(overrides, metadata);
    fs.writeFileSync(LIVE_CONFIG, configJS);

    return { configPath, filename };
}

/**
 * Git add, commit, and push the config changes.
 * Returns the commit hash or null on failure.
 */
function commitConfig(metadata = {}) {
    const cycle = metadata.cycle || '?';
    const winRate = metadata.winRate || '?';
    const diversity = metadata.diversity || '?';

    const msg = `balance: cycle ${cycle} — win ${winRate}% div ${diversity}%\n\nAuto-generated by self-play balance loop.\nOverrides applied to balance-config.js.`;

    try {
        // Stage the config files
        execSync('git add balance-config.js self-play/configs/ self-play/balance-result.json', {
            cwd: REPO_ROOT,
            stdio: 'pipe',
        });

        // Commit
        execSync(`git commit -m "${msg.replace(/"/g, '\\"')}"`, {
            cwd: REPO_ROOT,
            stdio: 'pipe',
        });

        // Get commit hash
        const hash = execSync('git rev-parse --short HEAD', {
            cwd: REPO_ROOT,
            stdio: 'pipe',
        }).toString().trim();

        return hash;
    } catch (e) {
        console.error(`Git commit failed: ${e.message}`);
        return null;
    }
}

/**
 * Push to remote.
 */
function pushConfig() {
    try {
        execSync('git push -u origin self-play', {
            cwd: REPO_ROOT,
            stdio: 'pipe',
            timeout: 30000,
        });
        return true;
    } catch (e) {
        console.error(`Git push failed: ${e.message}`);
        return false;
    }
}

module.exports = { writeConfig, commitConfig, pushConfig, formatConfigJS };
